version: "2"
services:
  web:
    build: .
    ports:
      - "4000:4000"
  cadvisor:
    image: google/cadvisor
    ports:
      - "8080:8080"
    volumes:
      - "/:/rootfs:ro"
      - "/var/run:/var/run:rw"
      - "/sys:/sys:ro"
      - "/var/lib/docker/:/var/lib/docker:ro"


